### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by tkriener** [jagregory/atom-pandoc-preview#22]
If I try to preview a Markdown-Page I get the following error.

I doesn't matter if pandoc is installed under ~/.cabal/bin/pandoc or if I install the official package uder /usr/local/bin.

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pandoc](https://github.com/jagregory/atom-pandoc-preview) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/kriener/.atom/packages/pandoc/lib/pandoc-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/kriener/.atom/packages/pandoc/lib/pandoc-view.coffee:4:199)
  at /Users/kriener/.atom/packages/pandoc/lib/pandoc-view.coffee:9:3
  at Object.<anonymous> (/Users/kriener/.atom/packages/pandoc/lib/pandoc-view.coffee:102:5)
  at Object.<anonymous> (/Users/kriener/.atom/packages/pandoc/lib/pandoc-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kriener/.atom/packages/pandoc/lib/pandoc.coffee:4:14)
  at Object.<anonymous> (/Users/kriener/.atom/packages/pandoc/lib/pandoc.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:256:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:261:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:306:24)
  at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:260:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by dkirkby** [comment]
I just installed pandoc and I am having the same problem with a simple .rst document in atom 1.0.0.

**Comment by jagregory** [comment]
I've just pushed a new version, which should fix this crash. There were some more Atom 1.0 changes which weren't caught by the Atom upgrade tool. Please install v0.2.2 from Atom.
