### ISSUE TITLE
Uncaught TypeError: this.getPath is not a function

### ISSUE THREAD

**Issue by deannachurch** [jagregory/atom-pandoc-preview#30]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [pandoc](https://github.com/jagregory/atom-pandoc-preview) package, v0.2.2
### Stack Trace

Uncaught TypeError: this.getPath is not a function

```
At /Users/deanna.church/.atom/packages/pandoc/lib/pandoc-view.coffee:27

TypeError: this.getPath is not a function
    at PandocView.module.exports.PandocView.serialize (/Users/deanna.church/.atom/packages/pandoc/lib/pandoc-view.coffee:27:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:23
    at Array.map (native)
    at Pane.module.exports.Pane.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:99:36)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:50:24
    at Array.map (native)
    at PaneAxis.module.exports.PaneAxis.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:49:33)
    at PaneContainer.module.exports.PaneContainer.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:54:51)
    at Workspace.module.exports.Workspace.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:154:43)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:770:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:27
```
### Commands

```
     -1:02.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:49.1.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:48.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:47.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41 core:move-up (atom-text-editor.editor.is-focused)
     -0:39.8.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:38.9.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:36.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:34.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:27.5.0 pandoc-preview:show (atom-text-editor.editor.is-focused)
     -0:19.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
linter-markdown, v1.5.0
markdown-preview-plus-opener, v0.2.0
pandoc, v0.2.2
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by IreneCrisologo** [comment]
+1 

Same issue :(

**Comment by digfish** [comment]
Here too :/

**Comment by evelyn** [comment]
Same here.

**Comment by horta** [comment]
Same here too :/

**Comment by khodadadp** [comment]
same here too!

**Comment by khodadadp** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [pandoc](https://github.com/jagregory/atom-pandoc-preview) package, v0.2.2

### Stack Trace

Uncaught TypeError: this.getPath is not a function

```
At /home/coco/.atom/packages/pandoc/lib/pandoc-view.coffee:27

TypeError: this.getPath is not a function
    at PandocView.module.exports.PandocView.serialize (/home/coco/.atom/packages/pandoc/lib/pandoc-view.coffee:27:16)
    at /usr/share/atom/resources/app.asar/src/pane.js:100:23
    at Array.map (native)
    at Pane.module.exports.Pane.serialize (/usr/share/atom/resources/app.asar/src/pane.js:99:36)
    at /usr/share/atom/resources/app.asar/src/pane-axis.js:50:24
    at Array.map (native)
    at PaneAxis.module.exports.PaneAxis.serialize (/usr/share/atom/resources/app.asar/src/pane-axis.js:49:33)
    at PaneContainer.module.exports.PaneContainer.serialize (/usr/share/atom/resources/app.asar/src/pane-container.js:54:51)
    at Workspace.module.exports.Workspace.serialize (/usr/share/atom/resources/app.asar/src/workspace.js:154:43)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:770:35)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -6:45.2.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
     -6:42.9.0 markdown-preview-plus:toggle-render-latex (atom-text-editor.editor.is-focused)
     -6:17.7.0 markdown-toc:toggle (ul.list-inline.tab-bar.inset-panel)
     -6:13.7.0 core:undo (atom-text-editor.editor.is-focused)
  4x -6:10.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:59.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -5:48 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:47.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:46.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:44.4.0 core:select-all (atom-text-editor.editor.is-focused)
  2x -5:44.1.0 core:copy (atom-text-editor.editor.is-focused)
     -4:38.7.0 markdown-preview-plus:sync-source (div.update-preview)
  2x -4:23.2.0 core:copy (td.)
     -3:17.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:45 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:17.3.0 pandoc-preview:show (div.package-detail.panels-item)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "pandoc": {}
}
```

### Installed Packages

``` coffee
# User
atom-python-run, v0.4.0
markdown-preview-plus, v2.4.0
markdown-toc, v0.4.1
pandoc, v0.2.2
pp-markdown, v0.0.2
python-indent, v0.4.3
python-tools, v0.6.8
remote-atom, v1.3.9

# Dev
No dev packages
```
